name: "Publish"

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: custom_components/unraid_companion

jobs:
  publish:
    name: "Publish"
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: "Zip component"
        run: |
          zip hass_unraid_companion.zip -r ./

      - name: "Upload assets"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} hass_unraid_companion.zip
